-- Supabase Schema Definition for Customer Support Chatbot MVP

-- 0. Optional: Enable the pgvector extension for future RAG / semantic search vector embeddings
CREATE EXTENSION IF NOT EXISTS vector;

-- 1. Stores Table
CREATE TABLE IF NOT EXISTS stores (
    id VARCHAR(100) PRIMARY KEY, -- e.g., 'hoverboard_store', 'hcs_gadgets', 'aroma_haven'
    name VARCHAR(255) NOT NULL,
    domain VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Support Articles Table (Whole documents)
CREATE TABLE IF NOT EXISTS support_articles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    store_id VARCHAR(100) NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Article Chunks Table (Sub-parts of articles, prepared for vector similarity lookup)
CREATE TABLE IF NOT EXISTS article_chunks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    article_id UUID NOT NULL REFERENCES support_articles(id) ON DELETE CASCADE,
    store_id VARCHAR(100) NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    embedding vector(1536), -- 1536 is standard for models like text-embedding-3-small or Gemini embeddings
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Conversations Table (Group chat messages by session)
CREATE TABLE IF NOT EXISTS conversations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    store_id VARCHAR(100) NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
    session_id VARCHAR(255) NOT NULL, -- UUID/String generated by frontend
    status VARCHAR(50) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'escalated', 'closed')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Messages Table
CREATE TABLE IF NOT EXISTS messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    conversation_id UUID NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    sender VARCHAR(50) NOT NULL CHECK (sender IN ('user', 'bot', 'agent')),
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Escalations Table (Tickets for human agents)
CREATE TABLE IF NOT EXISTS escalations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    conversation_id UUID NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    reason TEXT,
    status VARCHAR(50) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'resolved', 'ignored')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Staff Notes Table (Comments left by support dashboard agents)
CREATE TABLE IF NOT EXISTS staff_notes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    conversation_id UUID NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    author VARCHAR(255) NOT NULL, -- Name or email of the staff member
    note TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- =========================================================================
-- INDEXES FOR QUERY OPTIMIZATION
-- =========================================================================
CREATE INDEX IF NOT EXISTS idx_support_articles_store ON support_articles(store_id);
CREATE INDEX IF NOT EXISTS idx_article_chunks_store ON article_chunks(store_id);
CREATE INDEX IF NOT EXISTS idx_conversations_session ON conversations(session_id);
CREATE INDEX IF NOT EXISTS idx_messages_conversation ON messages(conversation_id);

-- =========================================================================
-- MOCK SEED DATA FOR STORES
-- =========================================================================
INSERT INTO stores (id, name, domain) VALUES
('hoverboard_store', 'Hoverboard Store UK', 'hoverboardstore.co.uk'),
('hcs_gadgets', 'HCS Gadgets', 'hcsgadgets.co.uk'),
('aroma_haven', 'Aroma Haven', 'aromahaven.co.uk')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, domain = EXCLUDED.domain;


-- =========================================================================
-- UNIFIED CHAT LOGS TABLE (For Simple Phase 2 MVP Chat Logging)
-- =========================================================================
CREATE TABLE IF NOT EXISTS chat_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    store_id VARCHAR(100) NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
    session_id VARCHAR(255) NOT NULL,
    user_message TEXT NOT NULL,
    assistant_message TEXT NOT NULL,
    matched_source VARCHAR(255),
    confidence DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    escalated BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(50) NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'needs_escalation', 'in_progress', 'resolved')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_chat_logs_session ON chat_logs(session_id);
CREATE INDEX IF NOT EXISTS idx_chat_logs_store ON chat_logs(store_id);

-- =========================================================================
-- MIGRATION (RUN THIS IF YOU ARE UPGRADING AN EXISTING DATABASE):
-- =========================================================================
-- ALTER TABLE chat_logs ADD COLUMN status VARCHAR(50) NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'needs_escalation', 'in_progress', 'resolved'));
-- UPDATE chat_logs SET status = 'needs_escalation' WHERE escalated = TRUE;
-- UPDATE chat_logs SET status = 'new' WHERE escalated = FALSE;


-- =========================================================================
-- HUMAN REPLY DRAFT BOX TABLE & TRIGGERS
-- =========================================================================
CREATE TABLE IF NOT EXISTS reply_drafts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id VARCHAR(255) UNIQUE NOT NULL,
    draft_text TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_reply_drafts_session ON reply_drafts(session_id);

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_reply_drafts_updated_at
    BEFORE UPDATE ON reply_drafts
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();


-- =========================================================================
-- AGENT SENT REPLIES TABLE
-- =========================================================================
CREATE TABLE IF NOT EXISTS agent_replies (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    session_id VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'sent',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_agent_replies_session ON agent_replies(session_id);


